### ISSUE TITLE
Define frontend purpose

### ISSUE THREAD

**Issue by endepointe** [SecurityLogMiner/log-collection-frontend#26]
There is some text to clear up from a previous merge conflict but at this point the frontend service has (or should still have) the following functionalities:

- authenticate a user
- make authorized requests to the API 

TLS remains unimplemented on the client and that may be something that requires specific setup configuration by AWS. 

However, the majority of the frontend repo remains vague and tasks should be defined for it.

Here are some options that I think would be good to work towards:
- create a dashboard that showed the status of the running client service
- create a visualization dashboard that represents the event types being read by the client

To make a request for the data, an api will be needed between the destination service (AWS) and frontend. The existing api repo could be used for that but there is a way to remove the need to have an api repo and give its responsibility to the frontend svelte application.

**Comment by Jicxer** [comment]
The Front-end will be archived for now. So far, we are using Svelte with auth0 for authentication, but we decided to focus on and prioritize the functionality of the log collection system rather than the appearance. 
I think it would be cool to have a front-end, but it should be minimized as a priority. 
**Let's open the front-end repo for now but not integrate it for any purpose.**
